#!/usr/bin/env bash
set -e

### Install BioLockJ.

### Any R packages should be handled in the Dockerfile.

echo "======== install BioLockJ ========"

# download BioLockJ
wget https://github.com/BioLockJ-Dev-Team/BioLockJ/releases/download/v1.4.2/BioLockJ-v1.4.2.tar.gz

# unpack BioLockJ
tar -zxf BioLockJ-v1.4.2.tar.gz
mv BioLockJ ~/BioLockJ
rm BioLockJ-v1.4.2.tar.gz

# install BioLockJ
cd ~/BioLockJ
./install

echo "======== test BioLockJ ========"

export BLJ=/root/BioLockJ
export BLJ_PROJ=$BLJ/pipelines
export PATH=$BLJ/script:$PATH

biolockj --version
biolockj --help
