---
title: "Heatmap Figure"
output: html_document
date: "2024-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
outDir = "../output/genus"
dir.create(outDir)
```

## 

Set up the outline of desired rows/columns for the heatmap.

Desired rows.
```{r}
metrics = c("Shannon Diversity",
            "Richness")

# names of elements are the manual labels.  
# element values should match the row names of the species-level heat map and p-value table from module 05_Taxonomy_vs_Features.
shortTaxaList = c("Ruminococcus" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Oscillospirales.f__Ruminococcaceae.g__Ruminococcus" ,
            "Ruminococcus torques group" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.g__.Ruminococcus._torques_group" ,
            "Ruminococcus gnavus group" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.g__.Ruminococcus._gnavus_group" ,
            "Oscillibacter" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Oscillospirales.f__Oscillospiraceae.g__Oscillibacter" ,
            "Phascolarctobacterium" = "d__Bacteria.p__Firmicutes.c__Negativicutes.o__Acidaminococcales.f__Acidaminococcaceae.g__Phascolarctobacterium" ,
            "Uncultured genus in the Oscillospiraceae family" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Oscillospirales.f__Oscillospiraceae.g__uncultured",# "g__uncultured (UB*)[34]",
            "Bifidobacterium" = "d__Bacteria.p__Actinobacteriota.c__Actinobacteria.o__Bifidobacteriales.f__Bifidobacteriaceae.g__Bifidobacterium",
            "Cloacibacillus" = "d__Bacteria.p__Synergistota.c__Synergistia.o__Synergistales.f__Synergistaceae.g__Cloacibacillus",
            "Clostridium sensu stricto" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Clostridiales.f__Clostridiaceae.g__Clostridium_sensu_stricto_2" ,
            "Faecalibacterium" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Oscillospirales.f__Ruminococcaceae.g__Faecalibacterium",
            "Akkermansia" = "d__Bacteria.p__Verrucomicrobiota.c__Verrucomicrobiae.o__Verrucomicrobiales.f__Akkermansiaceae.g__Akkermansia",
            "Lachnoclostridium" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.g__Lachnoclostridium",
            "Lachnospira" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.g__Lachnospira" ,
            "Holdemania" = "d__Bacteria.p__Firmicutes.c__Bacilli.o__Erysipelotrichales.f__Erysipelotrichaceae.g__Holdemania",
            "unspecified genus in the Lachnospiraceae family" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.__" ,
            "Parabacteroides" = "d__Bacteria.p__Bacteroidota.c__Bacteroidia.o__Bacteroidales.f__Tannerellaceae.g__Parabacteroides",
            "Streptococcus" = "d__Bacteria.p__Firmicutes.c__Bacilli.o__Lactobacillales.f__Streptococcaceae.g__Streptococcus",
            "Roseburia" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Lachnospirales.f__Lachnospiraceae.g__Roseburia",
            "Romboutsia" = "d__Bacteria.p__Firmicutes.c__Clostridia.o__Peptostreptococcales.Tissierellales.f__Peptostreptococcaceae.g__Romboutsia",
            "Methanobrevibacter" = "d__Archaea.p__Euryarchaeota.c__Methanobacteria.o__Methanobacteriales.f__Methanobacteriaceae.g__Methanobrevibacter")

write.table(cbind(shown=names(shortTaxaList), original=shortTaxaList), 
            file=file.path(outDir, "selected_taxa.txt"), 
            sep="\t", row.names=F)
```

Desired columns.
```{r}
cols = c('HC AD'="ANOREXIA.HCT1.Kruskal", 
         'HC DIS'="ANOREXIA.HCT2.Kruskal", 
         #'DIS vs AD' = "TIMEPOINT.T1T2.pairedT",
         #'DIS vs AD (ACUTE)' = "TIMEPOINT.T1T2.pairedT.acute",
         #'DIS vs AD (CEED)' = "TIMEPOINT.T1T2.pairedT.ceed",
         #'DIS vs AD (Fargo)' = "TIMEPOINT.T1T2.pairedT.fargo",
         'Subtype AD'="SUBTYPE.AN.HCT1.Kruskal", 
         'Subtype DIS'="SUBTYPE.AN.HCT2.Kruskal", 
         'Location AD'="LOCATION.HCT1.Kruskal", 
         'Location DIS'="LOCATION.HCT2.Kruskal", 
         'Weight AD'="Weight_kg.T1.kendall", 
         'Weight DIS'="Weight_kg.T2.kendall", 
         'BMI AD'="BMI.T1.kendall", 
         'BMI DIS'="BMI.T2.kendall", 
         'PSS AD'="PSS.T1.kendall", 
         'PSS DIS'="PSS.T2.kendall", 
         'State Anxiety AD'="STAI_Y1.T1.kendall", 
         'State Anxiety DIS'="STAI_Y1.T2.kendall", 
         'State Anxiety change'="STAI_Y1.diff.T1.kendall", 
         'Trait Anxiety AD'="STAI_Y2.T1.kendall", 
         'Trait Anxiety DIS'="STAI_Y2.T2.kendall",
         'Trait Anxiety change'="STAI_Y2.diff.T1.kendall"
         )

write.table(cbind(shown=names(cols), original=cols), 
            file=file.path(outDir, "selected_tests.txt"), 
            sep="\t", row.names=F)
```


Get the Diversity metrics.
```{r}
div.vs.feat.module = dir("../../", pattern="Diversity_vs_Features_AllSites", full.names = T)
diversity = read.delim2(file.path(div.vs.feat.module, "output/genus/bigList_pvalues_fdr-adjusted_genus.txt"))
row.names(diversity) = diversity$taxon
diversity = diversity[c("shannon.diversity", "richness"),]
row.names(diversity) = c("Shannon Diversity", "Richness")

# diversity$TIMEPOINT.T1T2.pairedT = NA
```

Get the taxonomy metrics.
```{r}
tax.vs.feat.module = dir("../../", pattern="Taxonomy_vs_Features", full.names = T)
taxa = read.delim2(file.path(tax.vs.feat.module, "output/genus/bigList_pvalues_fdr-adjusted_genus.txt"))

# select desired rows
row.names(taxa) = taxa$taxon.originalName
taxa = taxa[shortTaxaList, ]

#rename rows
row.names(taxa) = names(shortTaxaList)
```

Put them together.
```{r}
forHeat = rbind(diversity[ ,cols],
                taxa[ ,cols])
names(forHeat) = names(cols)
forHeat = forHeat %>% 
    mutate_if(is.character, as.numeric) %>%
    mutate_if(is.numeric, function(x){x[x > 0.05] = 1; return(x)})

write.table(cbind(labels=row.names(forHeat), forHeat), 
            file=file.path(outDir, "heatmap_values.txt"), 
            sep="\t", row.names=F, quote=F)
```


Heat map function.
```{r}
# source("../../05_Taxonomy_vs_Features/")

pvalTableToHeatMap = function(pvalTable, taxaLevel, midpointPval=0.05, bluePvalue=0.05, redPvalue=0.00001, title="-log10(p-values)", displayName.FUN=c, caption.notes=""){
    # pvalTable - data frame of pvalues, with columns corresponding to variables (metadata) and named rows for taxa_metrics.
    # bluePval - pvalues worse than this will all be shown in blue.
    # midpointPval - these will be shown in white, as a middle point between the blue and red gradients.
    # all p-values better than this will be shown in solid red.
    pvalTable[pvalTable < redPvalue] = redPvalue
    pvalTable[pvalTable > bluePvalue] = bluePvalue
    
    taxon = sapply( row.names(pvalTable), displayName.FUN )
    if (length(unique(taxon)) < nrow(pvalTable)){
        taxon = paste0(taxon, "[", 1:nrow(pvalTable), "]")
    }
    row.names(pvalTable) = taxon
    
    longTab = -log10(pvalTable) %>% 
        mutate(taxon= row.names(pvalTable) ) %>%
        pivot_longer(cols=-taxon, names_to = "var", values_to="pval")
    longTab$var = factor(x=as.character(longTab$var), levels=names(pvalTable))
    longTab$taxon = factor(x=as.character(longTab$taxon), levels=row.names(pvalTable))
    ggplot(longTab, aes(x=var, y=taxon, fill=pval)) +
      geom_tile(col="gray") +
      scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                           midpoint = -log10(midpointPval),
                           limit = c(-log10(bluePvalue),-log10(redPvalue)),
                           space = "Lab",
                           # name=paste0("p-value threshold: ", midpointPval, "\n\n-log10(p-value)"),
                           name="-log10(p-value)",
                           na.value = gray(.9)) +
      theme_minimal()+ # minimal theme
      ggtitle(title) +
      xlab("") +
      ylab("") +
      theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                       size = 8, hjust = 1)) +
      coord_fixed() +
      labs(caption=caption.notes)
}
```

```{r}
pvalTableToHeatMap(forHeat,midpointPval=0.1, bluePvalue=0.1,
                   title="-log10(adjusted p-values)",
                   caption.notes = "genus level")
```

Save to pdf.
```{r}
pdf(file.path(outDir, "heatMap_genus_main_fig.pdf"), width = 7, height = 10)

show(last_plot() + 
         labs(caption=paste(c("genus level - nonparametric tests", 
                              paste(names(cols), cols, sep=" = ")), 
                            collapse="\n")))

dev.off()
```


TODO
```{r}
# See url: https://www.tutorialspoint.com/how-to-write-partial-title-of-x-axis-in-italics-using-ggplot2-of-r
#.  expression(paste("X comes from ",italic("normal distribution")))
```

